// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID              pgtype.UUID
	Title           string
	Author          string
	Genre           string
	PublicationDate string
	ImageUrl        string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Review struct {
	ID        pgtype.UUID
	BookID    pgtype.UUID
	UserEmail string
	UserName  string
	Rating    int32
	Comment   string
	CreatedAt pgtype.Timestamptz
}
