// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (book_id, user_email, user_name, rating, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, book_id, user_email, user_name, rating, comment, created_at
`

type CreateReviewParams struct {
	BookID    pgtype.UUID
	UserEmail string
	UserName  string
	Rating    int32
	Comment   string
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.BookID,
		arg.UserEmail,
		arg.UserName,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.UserEmail,
		&i.UserName,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReviewsByBook = `-- name: DeleteReviewsByBook :exec
DELETE FROM reviews
WHERE book_id = $1
`

func (q *Queries) DeleteReviewsByBook(ctx context.Context, bookID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReviewsByBook, bookID)
	return err
}

const getReviewsByBook = `-- name: GetReviewsByBook :many
SELECT id, book_id, user_email, user_name, rating, comment, created_at FROM reviews
WHERE book_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetReviewsByBook(ctx context.Context, bookID pgtype.UUID) ([]Review, error) {
	rows, err := q.db.Query(ctx, getReviewsByBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.UserEmail,
			&i.UserName,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
